/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EfelantComposer {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "Message"
         */
        "placeholder": string;
    }
    interface EfelantContextFeed {
        "contextType": string;
        "externalId": string;
        "tenantId": string;
    }
    interface EfelantConversation {
        "contextType"?: string;
        "conversationId"?: string;
        "externalId"?: string;
        "tenantId": string;
    }
    interface EfelantConversationList {
        "tenantId"?: string;
    }
    interface EfelantStatusEvent {
        /**
          * @default ""
         */
        "message": string;
        /**
          * @default ""
         */
        "status": string;
    }
    interface EfelantUnreadBadge {
        /**
          * @default 0
         */
        "count": number;
    }
}
export interface EfelantComposerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEfelantComposerElement;
}
declare global {
    interface HTMLEfelantComposerElementEventMap {
        "efelantSend": string;
    }
    interface HTMLEfelantComposerElement extends Components.EfelantComposer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEfelantComposerElementEventMap>(type: K, listener: (this: HTMLEfelantComposerElement, ev: EfelantComposerCustomEvent<HTMLEfelantComposerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEfelantComposerElementEventMap>(type: K, listener: (this: HTMLEfelantComposerElement, ev: EfelantComposerCustomEvent<HTMLEfelantComposerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEfelantComposerElement: {
        prototype: HTMLEfelantComposerElement;
        new (): HTMLEfelantComposerElement;
    };
    interface HTMLEfelantContextFeedElement extends Components.EfelantContextFeed, HTMLStencilElement {
    }
    var HTMLEfelantContextFeedElement: {
        prototype: HTMLEfelantContextFeedElement;
        new (): HTMLEfelantContextFeedElement;
    };
    interface HTMLEfelantConversationElement extends Components.EfelantConversation, HTMLStencilElement {
    }
    var HTMLEfelantConversationElement: {
        prototype: HTMLEfelantConversationElement;
        new (): HTMLEfelantConversationElement;
    };
    interface HTMLEfelantConversationListElement extends Components.EfelantConversationList, HTMLStencilElement {
    }
    var HTMLEfelantConversationListElement: {
        prototype: HTMLEfelantConversationListElement;
        new (): HTMLEfelantConversationListElement;
    };
    interface HTMLEfelantStatusEventElement extends Components.EfelantStatusEvent, HTMLStencilElement {
    }
    var HTMLEfelantStatusEventElement: {
        prototype: HTMLEfelantStatusEventElement;
        new (): HTMLEfelantStatusEventElement;
    };
    interface HTMLEfelantUnreadBadgeElement extends Components.EfelantUnreadBadge, HTMLStencilElement {
    }
    var HTMLEfelantUnreadBadgeElement: {
        prototype: HTMLEfelantUnreadBadgeElement;
        new (): HTMLEfelantUnreadBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "efelant-composer": HTMLEfelantComposerElement;
        "efelant-context-feed": HTMLEfelantContextFeedElement;
        "efelant-conversation": HTMLEfelantConversationElement;
        "efelant-conversation-list": HTMLEfelantConversationListElement;
        "efelant-status-event": HTMLEfelantStatusEventElement;
        "efelant-unread-badge": HTMLEfelantUnreadBadgeElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface EfelantComposer {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onEfelantSend"?: (event: EfelantComposerCustomEvent<string>) => void;
        /**
          * @default "Message"
         */
        "placeholder"?: string;
    }
    interface EfelantContextFeed {
        "contextType": string;
        "externalId": string;
        "tenantId": string;
    }
    interface EfelantConversation {
        "contextType"?: string;
        "conversationId"?: string;
        "externalId"?: string;
        "tenantId": string;
    }
    interface EfelantConversationList {
        "tenantId"?: string;
    }
    interface EfelantStatusEvent {
        /**
          * @default ""
         */
        "message"?: string;
        /**
          * @default ""
         */
        "status"?: string;
    }
    interface EfelantUnreadBadge {
        /**
          * @default 0
         */
        "count"?: number;
    }

    interface EfelantComposerAttributes {
        "placeholder": string;
        "disabled": boolean;
    }
    interface EfelantContextFeedAttributes {
        "tenantId": string;
        "contextType": string;
        "externalId": string;
    }
    interface EfelantConversationAttributes {
        "tenantId": string;
        "conversationId": string;
        "contextType": string;
        "externalId": string;
    }
    interface EfelantConversationListAttributes {
        "tenantId": string;
    }
    interface EfelantStatusEventAttributes {
        "status": string;
        "message": string;
    }
    interface EfelantUnreadBadgeAttributes {
        "count": number;
    }

    interface IntrinsicElements {
        "efelant-composer": Omit<EfelantComposer, keyof EfelantComposerAttributes> & { [K in keyof EfelantComposer & keyof EfelantComposerAttributes]?: EfelantComposer[K] } & { [K in keyof EfelantComposer & keyof EfelantComposerAttributes as `attr:${K}`]?: EfelantComposerAttributes[K] } & { [K in keyof EfelantComposer & keyof EfelantComposerAttributes as `prop:${K}`]?: EfelantComposer[K] };
        "efelant-context-feed": Omit<EfelantContextFeed, keyof EfelantContextFeedAttributes> & { [K in keyof EfelantContextFeed & keyof EfelantContextFeedAttributes]?: EfelantContextFeed[K] } & { [K in keyof EfelantContextFeed & keyof EfelantContextFeedAttributes as `attr:${K}`]?: EfelantContextFeedAttributes[K] } & { [K in keyof EfelantContextFeed & keyof EfelantContextFeedAttributes as `prop:${K}`]?: EfelantContextFeed[K] } & OneOf<"tenantId", EfelantContextFeed["tenantId"], EfelantContextFeedAttributes["tenantId"]> & OneOf<"contextType", EfelantContextFeed["contextType"], EfelantContextFeedAttributes["contextType"]> & OneOf<"externalId", EfelantContextFeed["externalId"], EfelantContextFeedAttributes["externalId"]>;
        "efelant-conversation": Omit<EfelantConversation, keyof EfelantConversationAttributes> & { [K in keyof EfelantConversation & keyof EfelantConversationAttributes]?: EfelantConversation[K] } & { [K in keyof EfelantConversation & keyof EfelantConversationAttributes as `attr:${K}`]?: EfelantConversationAttributes[K] } & { [K in keyof EfelantConversation & keyof EfelantConversationAttributes as `prop:${K}`]?: EfelantConversation[K] } & OneOf<"tenantId", EfelantConversation["tenantId"], EfelantConversationAttributes["tenantId"]>;
        "efelant-conversation-list": Omit<EfelantConversationList, keyof EfelantConversationListAttributes> & { [K in keyof EfelantConversationList & keyof EfelantConversationListAttributes]?: EfelantConversationList[K] } & { [K in keyof EfelantConversationList & keyof EfelantConversationListAttributes as `attr:${K}`]?: EfelantConversationListAttributes[K] } & { [K in keyof EfelantConversationList & keyof EfelantConversationListAttributes as `prop:${K}`]?: EfelantConversationList[K] };
        "efelant-status-event": Omit<EfelantStatusEvent, keyof EfelantStatusEventAttributes> & { [K in keyof EfelantStatusEvent & keyof EfelantStatusEventAttributes]?: EfelantStatusEvent[K] } & { [K in keyof EfelantStatusEvent & keyof EfelantStatusEventAttributes as `attr:${K}`]?: EfelantStatusEventAttributes[K] } & { [K in keyof EfelantStatusEvent & keyof EfelantStatusEventAttributes as `prop:${K}`]?: EfelantStatusEvent[K] };
        "efelant-unread-badge": Omit<EfelantUnreadBadge, keyof EfelantUnreadBadgeAttributes> & { [K in keyof EfelantUnreadBadge & keyof EfelantUnreadBadgeAttributes]?: EfelantUnreadBadge[K] } & { [K in keyof EfelantUnreadBadge & keyof EfelantUnreadBadgeAttributes as `attr:${K}`]?: EfelantUnreadBadgeAttributes[K] } & { [K in keyof EfelantUnreadBadge & keyof EfelantUnreadBadgeAttributes as `prop:${K}`]?: EfelantUnreadBadge[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "efelant-composer": LocalJSX.IntrinsicElements["efelant-composer"] & JSXBase.HTMLAttributes<HTMLEfelantComposerElement>;
            "efelant-context-feed": LocalJSX.IntrinsicElements["efelant-context-feed"] & JSXBase.HTMLAttributes<HTMLEfelantContextFeedElement>;
            "efelant-conversation": LocalJSX.IntrinsicElements["efelant-conversation"] & JSXBase.HTMLAttributes<HTMLEfelantConversationElement>;
            "efelant-conversation-list": LocalJSX.IntrinsicElements["efelant-conversation-list"] & JSXBase.HTMLAttributes<HTMLEfelantConversationListElement>;
            "efelant-status-event": LocalJSX.IntrinsicElements["efelant-status-event"] & JSXBase.HTMLAttributes<HTMLEfelantStatusEventElement>;
            "efelant-unread-badge": LocalJSX.IntrinsicElements["efelant-unread-badge"] & JSXBase.HTMLAttributes<HTMLEfelantUnreadBadgeElement>;
        }
    }
}
