changelog:
  exclude:
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: Security
      labels:
        - security
    - title: Breaking changes
      labels:
        - breaking
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Other
      labels:
        - "*"
