apiVersion: v1
kind: Service
metadata:
  name: efelant-web
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: efelant
    app.kubernetes.io/component: web
