apiVersion: apps/v1
kind: Deployment
metadata:
  name: efelant-web
  labels:
    app.kubernetes.io/name: efelant
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: efelant
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: efelant
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: efelant-web:0.1.0
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
