server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  absolute_redirect off;

  location / {
    try_files $uri $uri/ $uri.html =404;
  }

  location = /docs {
    return 302 /docs/;
  }

  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy same-origin always;
}
