apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - sgcluster.yaml
patches:
  - target:
      kind: ConfigMap
      name: efelant
    patch: |-
      - op: replace
        path: /data/POSTGRES_HOST
        value: efelant-postgres
