import { mkdirSync, writeFileSync, cpSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import StyleDictionary from "style-dictionary";

const root = dirname(fileURLToPath(import.meta.url));
const repo = join(root, "../..");

function flatten(node, path = []) {
  if (!node || typeof node !== "object") {
    return [];
  }
  if ("value" in node || "$value" in node) {
    return [{ path, $value: node.$value ?? node.value, $type: node.$type ?? node.type }];
  }
  return Object.entries(node).flatMap(([key, child]) => flatten(child, [...path, key]));
}

function loadJson(...rel) {
  return flatten(JSON.parse(readFileSync(join(root, ...rel), "utf8")));
}

function cssVarName(path) {
  return `--ef-${path.join("-")}`;
}

function cssValue(token) {
  if (token.$type === "dimension" || token.$type === "fontSize") {
    return `${token.$value}px`;
  }
  return String(token.$value);
}

function hexToFlutter(hex) {
  const h = String(hex).replace("#", "").toUpperCase();
  return `Color(0x${h.length === 6 ? `FF${h}` : h})`;
}

function dartName(path) {
  return path
    .map((part, i) => {
      const camel = part.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
      return i === 0 ? camel : camel.charAt(0).toUpperCase() + camel.slice(1);
    })
    .join("");
}

function formatCss(tokens, selector) {
  const lines = tokens.map((t) => `  ${cssVarName(t.path)}: ${cssValue(t)};`);
  return `${selector} {\n${lines.join("\n")}\n}\n`;
}

function formatJs(name, tokens) {
  const body = tokens
    .map((t) => `  "${t.path.join(".")}": ${JSON.stringify(String(t.$value))},`)
    .join("\n");
  return `export const ${name} = {\n${body}\n};\n`;
}

function formatDartClass(className, tokens) {
  const fields = tokens.map((t) => {
    const name = dartName(t.path);
    switch (t.$type) {
      case "color":
        return `  static const Color ${name} = ${hexToFlutter(t.$value)};`;
      case "dimension":
      case "fontSize":
        return `  static const double ${name} = ${Number(t.$value)}.0;`;
      case "fontWeight":
        return `  static const FontWeight ${name} = FontWeight.w${t.$value};`;
      default:
        return `  static const String ${name} = ${JSON.stringify(String(t.$value))};`;
    }
  });
  return [`abstract final class ${className} {`, ...fields, "}"].join("\n");
}

StyleDictionary.registerFormat({
  name: "efelant/css-primary",
  format: ({ dictionary }) =>
    formatCss(dictionary.allTokens, ':root, [data-efelant-theme="primary"]'),
});
StyleDictionary.registerFormat({
  name: "efelant/css-secondary",
  format: ({ dictionary }) =>
    formatCss(dictionary.allTokens, '[data-efelant-theme="secondary"]'),
});

const core = loadJson("tokens/core.json");
const primaryColors = loadJson("tokens/color/primary.json");
const secondaryColors = loadJson("tokens/color/secondary.json");
const primary = [...core, ...primaryColors];
const secondary = [...core, ...secondaryColors];

const cssDir = join(root, "dist/css");
const jsDir = join(root, "dist/js");
mkdirSync(cssDir, { recursive: true });
mkdirSync(jsDir, { recursive: true });

const primaryCss = formatCss(primary, ':root, [data-efelant-theme="primary"]');
const secondaryCss = formatCss(secondary, '[data-efelant-theme="secondary"]');
writeFileSync(join(cssDir, "primary.css"), primaryCss);
writeFileSync(join(cssDir, "secondary.css"), secondaryCss);
writeFileSync(join(cssDir, "tokens.css"), `${primaryCss}\n${secondaryCss}`);
writeFileSync(
  join(jsDir, "tokens.js"),
  `${formatJs("efelantCore", core)}\n${formatJs("efelantPrimary", primary)}\n${formatJs("efelantSecondary", secondary)}export const themes = { primary: efelantPrimary, secondary: efelantSecondary };\n`,
);

const dartPath = join(repo, "packages/flutter/lib/src/generated/tokens.g.dart");
mkdirSync(dirname(dartPath), { recursive: true });
writeFileSync(
  dartPath,
  [
    "// GENERATED by packages/tokens. Do not edit.",
    "import 'package:flutter/material.dart';",
    "",
    formatDartClass("EfelantTokens", primary),
    "",
    formatDartClass("EfelantTokensSecondary", secondary),
    "",
  ].join("\n"),
);

const stencilTokens = join(repo, "packages/web-components/src/global/tokens.css");
mkdirSync(dirname(stencilTokens), { recursive: true });
cpSync(join(cssDir, "tokens.css"), stencilTokens);

const siteTokens = join(repo, "site/css/tokens.css");
mkdirSync(dirname(siteTokens), { recursive: true });
cpSync(join(cssDir, "tokens.css"), siteTokens);

const sdPrimary = new StyleDictionary({
  source: [join(root, "tokens/core.json"), join(root, "tokens/color/primary.json")],
  platforms: {
    css: {
      buildPath: join(root, "dist/sd/"),
      files: [{ destination: "primary.check.css", format: "efelant/css-primary" }],
    },
  },
});
await sdPrimary.buildAllPlatforms();

console.log("tokens: css + js + dart + stencil + site");
