#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${1:-$ROOT/.env}"

if [ -f "$DEST" ]; then
  echo "refusing to overwrite $DEST" >&2
  exit 1
fi

rand() {
  openssl rand -base64 32 | tr -d '\n='
}

APP_PASSWORD="$(rand)"

cat >"$DEST" <<EOF
# Generated by scripts/new-secrets.sh. Do not commit.

POSTGRES_USER=postgres
POSTGRES_PASSWORD=$(rand)
POSTGRES_DB=efelant

EFELANT_MIGRATOR_PASSWORD=$(rand)
EFELANT_APP_PASSWORD=${APP_PASSWORD}

EFELANT_DB_HOST=localhost
EFELANT_DB_PORT=5432
EFELANT_DB_NAME=efelant
EFELANT_DB_USER=efelant_app
EFELANT_DB_PASSWORD=${APP_PASSWORD}
EFELANT_DB_SSLMODE=disable

EFELANT_WEB_PORT=8080
EFELANT_SEED=0
EFELANT_DOMAIN=chat.example.com
EFELANT_WS_ORIGINS=https://chat.example.com
EOF

echo "wrote $DEST"
echo "set EFELANT_DOMAIN and EFELANT_WS_ORIGINS before using docker-compose.caddy.yml"
