apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: efelant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`chat.example.com`) && PathPrefix(`/ws`)
      kind: Rule
      middlewares:
        - name: efelant-ws
      services:
        - name: efelant-gateway
          port: 5433
    - match: Host(`chat.example.com`)
      kind: Rule
      middlewares:
        - name: efelant-compress
      services:
        - name: efelant-web
          port: 80
  tls:
    certResolver: letsencrypt
